import 'package:alaya/core/enums/shopping_enums.dart';
import 'package:alaya/core/money/money.dart';
import 'package:alaya/core/quantity/qty.dart';
import 'package:alaya/core/time/date_key.dart';

/// An intent to buy something. May or may not link to a catalogued `Item`.
///
/// [origin], [autoState] and [stockAtGeneration] together are what make low-stock auto-generation
/// idempotent *and* dismissible without the entry reappearing on the next run (anomalies A22, A23).
class ShoppingEntry {
  /// Creates an entry.
  const ShoppingEntry({
    required this.id,
    required this.listId,
    required this.origin,
    required this.autoState,
    required this.isChecked,
    required this.sortOrder,
    this.itemId,
    this.freeText,
    this.quantity,
    this.unitCode,
    this.tagId,
    this.estimatedPrice,
    this.checkedAtUtc,
    this.snoozeUntilDateKey,
    this.stockAtGeneration,
    this.purchasedTransactionLineId,
  });

  /// Identifier, UUIDv7.
  final String id;

  /// The list this entry belongs to.
  final String listId;

  /// How this entry came to exist. Editing an auto entry promotes it to `manual`, after which the
  /// suggestion engine never removes it.
  final ShoppingEntryOrigin origin;

  /// Lifecycle of an auto-generated entry, so a dismissal survives the next regeneration.
  final ShoppingEntryAutoState autoState;

  /// Ticked off in the list.
  final bool isChecked;

  /// Manual ordering within its group.
  final int sortOrder;

  /// The catalogued item, when this entry refers to one. Null lets `TV ☐` work without inventing
  /// an inventory item (anomaly A24).
  final String? itemId;

  /// What to buy, when there is no [itemId].
  final String? freeText;

  /// How much to buy, or null to render no quantity at all rather than a misleading `0`.
  final Qty? quantity;

  /// The unit the user typed, for display.
  final String? unitCode;

  /// The group header this entry appears under — `Grocery`, `Beauty`, `Electronics`.
  final String? tagId;

  /// Optional expected price, for the running list estimate.
  final Money? estimatedPrice;

  /// When it was ticked. Always UTC.
  final DateTime? checkedAtUtc;

  /// Hide an auto entry until this civil date.
  final DateKey? snoozeUntilDateKey;

  /// The item's total stock when this entry was auto-generated — the comparison point that stops a
  /// dismissed suggestion returning until stock has genuinely risen and fallen again.
  final Qty? stockAtGeneration;

  /// The transaction line that fulfilled this entry (anomaly A25).
  final String? purchasedTransactionLineId;

  /// What to show on the row: the free text, or null when the caller should resolve [itemId]'s
  /// name instead.
  String? get displayLabel => freeText;

  /// True when this entry was generated rather than typed.
  bool get isAutoGenerated => origin == ShoppingEntryOrigin.autoLowStock;

  /// True when this entry has been converted into an actual purchase.
  bool get isPurchased => purchasedTransactionLineId != null;

  /// True when an auto entry should currently be visible in the list.
  ///
  /// A snoozed entry becomes visible again once [snoozeUntilDateKey] has passed; a dismissed one
  /// does not return on a date at all — only on the stock condition re-triggering, which the
  /// suggestion engine decides using [stockAtGeneration].
  bool isVisibleAsOf(DateKey today) {
    if (!isAutoGenerated) return true;
    return switch (autoState) {
      ShoppingEntryAutoState.active => true,
      ShoppingEntryAutoState.dismissed => false,
      ShoppingEntryAutoState.snoozed =>
        snoozeUntilDateKey != null && !today.isBefore(snoozeUntilDateKey!),
    };
  }

  /// True when this entry is still something to buy.
  ///
  /// **Visibility and outstandingness are different questions.** `isVisibleAsOf` answers whether an
  /// auto suggestion has been snoozed or turned down. This also excludes anything already bought: a
  /// list is a list of what to get, and an entry fulfilled by a committed transaction is done.
  ///
  /// It is filtered rather than deleted. `purchasedTransactionLineId` is the provenance of the line
  /// that bought it, and removing the row would break the only link between a receipt and the list it
  /// came from (Law L6).
  bool isOutstandingAsOf(DateKey today) => !isPurchased && isVisibleAsOf(today);

  /// A copy with the given fields replaced. See [Currency.copyWith] on clearing nullables.
  ShoppingEntry copyWith({
    String? id,
    String? listId,
    ShoppingEntryOrigin? origin,
    ShoppingEntryAutoState? autoState,
    bool? isChecked,
    int? sortOrder,
    String? itemId,
    String? freeText,
    Qty? quantity,
    String? unitCode,
    String? tagId,
    Money? estimatedPrice,
    DateTime? checkedAtUtc,
    DateKey? snoozeUntilDateKey,
    Qty? stockAtGeneration,
    String? purchasedTransactionLineId,
  }) {
    return ShoppingEntry(
      id: id ?? this.id,
      listId: listId ?? this.listId,
      origin: origin ?? this.origin,
      autoState: autoState ?? this.autoState,
      isChecked: isChecked ?? this.isChecked,
      sortOrder: sortOrder ?? this.sortOrder,
      itemId: itemId ?? this.itemId,
      freeText: freeText ?? this.freeText,
      quantity: quantity ?? this.quantity,
      unitCode: unitCode ?? this.unitCode,
      tagId: tagId ?? this.tagId,
      estimatedPrice: estimatedPrice ?? this.estimatedPrice,
      checkedAtUtc: checkedAtUtc ?? this.checkedAtUtc,
      snoozeUntilDateKey: snoozeUntilDateKey ?? this.snoozeUntilDateKey,
      stockAtGeneration: stockAtGeneration ?? this.stockAtGeneration,
      purchasedTransactionLineId:
          purchasedTransactionLineId ?? this.purchasedTransactionLineId,
    );
  }

  @override
  bool operator ==(Object other) =>
      other is ShoppingEntry &&
      other.id == id &&
      other.listId == listId &&
      other.origin == origin &&
      other.autoState == autoState &&
      other.isChecked == isChecked &&
      other.sortOrder == sortOrder &&
      other.itemId == itemId &&
      other.freeText == freeText &&
      other.quantity == quantity &&
      other.unitCode == unitCode &&
      other.tagId == tagId &&
      other.estimatedPrice == estimatedPrice &&
      other.checkedAtUtc == checkedAtUtc &&
      other.snoozeUntilDateKey == snoozeUntilDateKey &&
      other.stockAtGeneration == stockAtGeneration &&
      other.purchasedTransactionLineId == purchasedTransactionLineId;

  @override
  int get hashCode => Object.hashAll([
    id,
    listId,
    origin,
    autoState,
    isChecked,
    sortOrder,
    itemId,
    freeText,
    quantity,
    unitCode,
    tagId,
    estimatedPrice,
    checkedAtUtc,
    snoozeUntilDateKey,
    stockAtGeneration,
    purchasedTransactionLineId,
  ]);

  @override
  String toString() => 'ShoppingEntry($id, ${freeText ?? itemId})';
}
