/// View-model state for the low-stock suggestion sheet (ARCH_5 U19).
library;

import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'package:alaya/app/providers/repository_providers.dart';
import 'package:alaya/core/enums/shopping_enums.dart';
import 'package:alaya/core/quantity/qty.dart';
import 'package:alaya/domain/entities/item.dart';
import 'package:alaya/domain/entities/shopping_entry.dart';
import 'package:alaya/features/shopping/providers/shopping_list_providers.dart';

/// One suggestion, with the shortfall that produced it.
class LowStockSuggestion {
  /// Creates a suggestion.
  const LowStockSuggestion({required this.entry, this.item, this.shortfall});

  /// The auto-generated entry.
  final ShoppingEntry entry;

  /// The item it restocks.
  final Item? item;

  /// How far below its low-stock level the item sat when the suggestion was made.
  final Qty? shortfall;
}

/// The active suggestions on one list, with their shortfalls.
///
/// **Shortfall is `threshold − stockAtGeneration`, both stored on the entry's own history.** Reading
/// live stock instead would make the figure drift between the sheet opening and the user acting on
/// it, and `stockAtGeneration` exists precisely so a suggestion can explain itself after the fact.
final lowStockSuggestionsProvider = Provider.autoDispose
    .family<AsyncValue<List<LowStockSuggestion>>, String>((ref, listId) {
      final entries = ref.watch(entriesProvider(listId));
      final items = ref.watch(shoppingItemsByIdProvider);
      if (entries.hasError)
        return AsyncValue.error(entries.error!, entries.stackTrace!);
      final rows = entries.valueOrNull;
      if (rows == null) return const AsyncValue.loading();
      final byId = items.valueOrNull ?? const <String, Item>{};

      return AsyncValue.data([
        for (final entry in rows)
          // Bought ones drop off: the stock that prompted the suggestion has arrived, so it is no longer a
          // suggestion. Snoozed and dismissed ones stay, because this sheet is where they are reconsidered.
          if (entry.isAutoGenerated && !entry.isPurchased)
            LowStockSuggestion(
              entry: entry,
              item: entry.itemId == null ? null : byId[entry.itemId],
              shortfall: _shortfall(
                entry,
                entry.itemId == null ? null : byId[entry.itemId],
              ),
            ),
      ]);
    });

Qty? _shortfall(ShoppingEntry entry, Item? item) {
  final threshold = item?.lowStockThreshold;
  final atGeneration = entry.stockAtGeneration;
  if (threshold == null || atGeneration == null) return null;
  if (threshold.category != atGeneration.category) return null;
  final gap = threshold - atGeneration;
  return gap.isPositive ? gap : null;
}

/// Runs low-stock generation for a list.
final generateActionsProvider = Provider<GenerateActions>(GenerateActions.new);

/// Regenerates suggestions.
class GenerateActions {
  /// Creates the actions.
  GenerateActions(this._ref);

  final Ref _ref;

  /// Regenerates and returns how many suggestions are now active, or null on failure.
  ///
  /// The repository's own contract guarantees this is idempotent: running it repeatedly neither
  /// duplicates entries nor resurrects dismissed ones (anomalies A22, A23). Nothing here re-derives
  /// that, because a second implementation is a second thing to get wrong.
  /// Accepts a suggestion, making it the user's own entry.
  ///
  /// **Promotes it to `origin = manual`.** Affirmatively choosing a suggestion is exactly what makes
  /// it yours, and a manual entry is never auto-removed or rewritten by regeneration (anomaly A23).
  /// It also un-dismisses and un-snoozes it, which is the only way back from "Not now" — without
  /// this, turning a suggestion down was irreversible until stock recovered and dropped again.
  Future<String?> accept(ShoppingEntry entry) async {
    final saved = await _ref
        .read(shoppingRepositoryProvider)
        .saveEntry(
          entry.copyWith(
            origin: ShoppingEntryOrigin.manual,
            autoState: ShoppingEntryAutoState.active,
          ),
        );
    return saved.failureOrNull?.message;
  }

  Future<({int? added, String? error})> regenerate(String listId) async {
    final result = await _ref
        .read(shoppingRepositoryProvider)
        .regenerateLowStockSuggestions(listId);
    final failure = result.failureOrNull;
    return failure == null
        ? (added: result.valueOrNull ?? 0, error: null)
        : (added: null, error: failure.message);
  }
}
